on:
  push:
    branches:
        - '*'
        - '!master'
  pull_request:
    branches:
        - 'master'

name: Test frontend build

jobs:
  docker-build:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build frontend
        run: |
          pushd src/frontend
          npm install
          npm run lint
          npm run generate
          popd